import { Space_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/navbar";
const inter = Inter({ subsets: ["latin"] });
// const monospace = Space_Mono({ subsets: ["latin"], weight: ["700"] });

export const metadata = {
  title: "Jackal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" id="light">
      <body className={inter.className}>
        <div className="-z-30 absolute h-full w-full bg-[radial-gradient(var(--bgdot)_1px,transparent_1px)] [background-size:16px_16px] [mask-image:radial-gradient(ellipse_50%_50%_at_50%_50%,#000_70%,transparent_100%)] "></div>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
//
